<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>c8y.example</groupId>
        <artifactId>c8y-examples</artifactId>
        <version>${revision}${changelist}</version>
    </parent>

    <groupId>c8y.example.mqtt-service</groupId>
    <artifactId>mqtt-service-examples</artifactId>
    <version>${revision}${changelist}</version>
    <name>Cumulocity :: Examples :: MQTT Service</name>
    <packaging>pom</packaging>

    <modules>
        <module>java-simple-pulsar-client</module>
        <module>java-pulsar-microservice</module>
    </modules>

    <build>
        <plugins>
            <plugin>
                <artifactId>maven-enforcer-plugin</artifactId>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
