#application.name=hello-world
server.port=8082

# This parameter is provided by platform for microservice deployed in cumulocity.
# You can set it up to your dedicated cumulocity address. You can get one by trying free trial on www.cumulocity.com
#C8Y.baseURL=

application.name=otlp-hello
C8Y.bootstrap.register=true
C8Y.bootstrap.tenant=management
C8Y.baseURL=http://cumulocity.default.svc.cluster.local
C8Y.bootstrap.user=servicebootstrap_otlp-hello
C8Y.bootstrap.password=7v4f6EBD3Y1k9N509XJvvalArglM65Yq
C8Y.microservice.isolation=MULTI_TENANT

# for RefreshScope:
spring.cloud.config.enabled=false
#management.endpoints.web.exposure.include=refresh


# OTLP configuration:
#=============================================================
# turn on/off implicit automatic JVM metrics generation
otel.sdk.disabled=false
otel.metric.export.interval=5555

otel.exporter.otlp.timeout=9999

#otel.service.name=hello-sdk2-otel
#otel.traces.exporter=otlp
otel.traces.exporter=console
#otel.metrics.exporter=otlp
otel.metrics.exporter=console
#otel.logs.exporter=otlp
otel.logs.exporter=console

otel.log.level=debug

otel.exporter.otlp.protocol=http/protobuf
#otel.exporter.otlp.protocol=grpc
#otel.exporter.otlp.endpoint=https://otlp-gateway-prod-eu-west-2.grafana.net/
#otel.exporter.otlp.endpoint=https://otlp-gateway-prod-eu-west-2.grafana.net/otlp/
otel.exporter.otlp.endpoint=https://otlp-gateway-prod-eu-west-2.grafana.net/otlp/v1/metrics
otel.exporter.otlp.metrics.endpoint=https://otlp-gateway-prod-eu-west-2.grafana.net/otlp/v1/metrics

otel.exporter.otlp.headers="Authorization=Basic MTAxNTI0OTpnbGNfZXlKdklqb2lNVEl3TURJek55SXNJbTRpT2lKemRHRmpheTB4TURFMU1qUTVMVzkwYkhBdGQzSnBkR1V0YUdWc2JHOHRiM1JzY0NJc0ltc2lPaUl6TVZCMlIyaE1Vek13UkRZMk9VcE5TVFZCTW5Jd1dXa2lMQ0p0SWpwN0luSWlPaUp3Y205a0xXVjFMWGRsYzNRdE1pSjlmUT09"
#otel.exporter.otlp.headers='Authorization="Basic MTAxNTI0OTpnbGNfZXlKdklqb2lNVEl3TURJek55SXNJbTRpT2lKemRHRmpheTB4TURFMU1qUTVMVzkwYkhBdGQzSnBkR1V0YUdWc2JHOHRiM1JzY0NJc0ltc2lPaUl6TVZCMlIyaE1Vek13UkRZMk9VcE5TVFZCTW5Jd1dXa2lMQ0p0SWpwN0luSWlPaUp3Y205a0xXVjFMWGRsYzNRdE1pSjlmUT09"'

otel.resource.attributes=service.name=hello-sdk30,deployment.environment=staging,service.namespace=foo,service.version=beta,service.instance.id=12345
#otel.resource.attributes=deployment.environment=staging,service.namespace=foo,service.instance.id=12345



#export OTEL_EXPORTER_OTLP_PROTOCOL="http/protobuf"
#export OTEL_EXPORTER_OTLP_ENDPOINT="https://otlp-gateway-prod-eu-west-2.grafana.net/otlp"
#export OTEL_EXPORTER_OTLP_HEADERS="Authorization=Basic MTAxNTI0OTpnbGNfZXlKdklqb2lNVEl3TURJek55SXNJbTRpT2lKemRHRmpheTB4TURFMU1qUTVMVzkwYkhBdGQzSnBkR1V0YUdWc2JHOHRiM1JzY0NJc0ltc2lPaUl6TVZCMlIyaE1Vek13UkRZMk9VcE5TVFZCTW5Jd1dXa2lMQ0p0SWpwN0luSWlPaUp3Y205a0xXVjFMWGRsYzNRdE1pSjlmUT09"

#from deployment of java agent instrumented:
#env:
#- name: JAVA_OPTS_APPEND
#value: -javaagent:/opentelemetry-javaagent.jar -Xms768m -Xmx1536m
#- name: OTEL_RESOURCE_ATTRIBUTES
#value: service.name=keycloak,service.version=test,deployment.environment=qa
#- name: OTEL_EXPORTER_OTLP_ENDPOINT
#value: https://aaa:443
#- name: OTEL_EXPORTER_OTLP_HEADERS
#value: Authorization=Bearer xxxx
#- name: OTEL_METRICS_EXPORTER
#value: otlp
#- name: OTEL_LOGS_EXPORTER
#value: otlp
#- name: OTEL_TRACES_EXPORTER
#value: otlp
#- name: OTEL_EXPORTER_OTLP_PROTOCOL
#value: http/protobuf
#
#OTEL_METRIC_EXPORT_INTERVAL=15000

#--------------------------------------------------------
# reanimate:
###
###
#### turn on/off implicit automatic JVM metrics generation
###otel.sdk.disabled=false
###
####otel.propagators=tracecontext
####otel.resource.attributes.deployment.environment=dev
####otel.resource.attributes.service.name=hello-sdk
####otel.resource.attributes.service.version=test
####otel.resource.attributes.service.namespace=poc
####otel.exporter.otlp.endpoint=http://grafana:443
###otel.service.name=hello-sdk2
####otel.traces.exporter=otlp
###otel.traces.exporter=console
####otel.metrics.exporter=otlp
###otel.metrics.exporter=console
####otel.logs.exporter=otlp
###otel.logs.exporter=console
###
###otel.exporter.otlp.protocol=http/protobuf
####otel.exporter.otlp.protocol=grpc
###otel.exporter.otlp.endpoint=https://otlp-gateway-prod-eu-west-2.grafana.net/otlp
####otel.exporter.otlp.endpoint=https://otlp-gateway-prod-eu-west-2.grafana.net/otlp/v1/metrics
###otel.exporter.otlp.headers="Authorization=Basic MTAxNTI0OTpnbGNfZXlKdklqb2lNVEl3TURJek55SXNJbTRpT2lKemRHRmpheTB4TURFMU1qUTVMVzkwYkhBdGQzSnBkR1V0YUdWc2JHOHRiM1JzY0NJc0ltc2lPaUl6TVZCMlIyaE1Vek13UkRZMk9VcE5TVFZCTW5Jd1dXa2lMQ0p0SWpwN0luSWlPaUp3Y205a0xXVjFMWGRsYzNRdE1pSjlmUT09"
###
####export OTEL_SERVICE_NAME=<< SERVICE >>
####export OTEL_RESOURCE_ATTRIBUTES=deployment.environment=<< ENVIRONMENT >>,service.namespace=<< NAMESPACE >>,service.version=<< VERSION >>,service.instance.id=<< ID >>
###otel.resource.attributes=service.name=hello-sdk3,deployment.environment=staging,service.namespace=foo,service.version=beta,service.instance.id=12345
###